apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  namespace: production
  annotations:
    # Mappings EKS ServiceAccount to the AWS IAM Role
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/payment-service-dynamodb-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
